In [1]:
import pandas as pd
import numpy as np
import math
import random
from datetime import datetime

In [2]:
df_card_port_cons = pd.DataFrame(columns=['per_num',
'vintage',
'product',
'prod_grp',
'prod_type',
'wallet_size',
'wallet_segment',
'cfo_revlv_ind',
'open_ind',
'spend_type',
'segment',
'ga_ind',
'graduated_ind',
'conv_ind',
'college_ind',
'accts_enr',
'accts_open',
'accts_active_bill',
'accts_active_sales',
'accts_bill_inactv_l12',
'accts_sales_inactive_l12',
'accts_new_acquired',
'accts_closed_new',
'accts_closed_vol',
'accts_closed_invol',
'accts_inactive_closed',
'accts_otherinvol_closed',
'accts_new_balcon',
'accts_enr_delq_26',
'accts_ncl',
'fico_score',
'fico_score_accts',
'accts_acctonlin_ever',
'accts_paperless_ever',
'accts_auth_primary_only',
'accts_auth_secondary',
'accts_auth_multiple',
'sales_purch',
'sales_offus',
'sales_new_balcon_ant',
'bal_anr',
'bal_enr',
'bal_bnr',
'bal_delnq_26',
'bal_full_rate_offus',
'bal_promo_offus',
'bal_rvlv_offus_bur',
'bal_rvlv_offus_argus',
'credt_limit_onus',
'pay_amt',
'pay_rate',
'bal_revolving',
'net_interest',
'cof',
'Interchange',
'fee_total',
'rebate',
'cnr',
'ebit',
'ncl',
'refill_points_rewplus',
'roundup_points_rewplus',
'points_back_10ptc_rewplus',
'Incap_2x_points_back_rewplus',
'metcap_1x_points_back_rewplus',
'acq_bonus_points',
'bonus_points',
'bal_bseg_intro_bt',
'bal_bseg_intro_spl',
'bal_bseg_intro_purch_promo',
'bal_bseg_intro_others',
'bal_bseg_goto',
'bal_bseg_risk',
'bal_bseg_flex_loan',
'bal_bseg_flex_pay',
'bal_bseg_amazon_pos',
'accts_bseg_flex_loan',
'accts_bseg_flex_pay',
'accts_bseg_amazon_pos',
'sales_bseg_flex_loan',
'sales_bseg_flex_pay',
'sales_bseg_amazon_pos',
'expedia_sales',
'travel_portal_sales',
'sb_capped_spend',
'spend1_airlines',
'txn_airlines',
'spend1_dining',
'txn_dining',
'spend1_entertainment',
'txn_entertainment',
'spend1_electronics',
'txn_electronics',
'spend1_home_Improvement',
'txn_house_improvement',
'spend1_grocery',
'txn_grocery',
'spend1_hotels_motels',
'txn_hotels_motels',
'spend_other_travel',
'spend_gas',
'txn_gas',
'txn_other_travel',
'spend_cruise',
'txn_cruise',
'spend1_total',
'txn_total',
'accts_airlines',
'accts_dining',
'accts_entertainment',
'accts_electronics',
'accts_home_improvement',
'accts_grocery',
'accts_hotels_motels',
'accts_other_travel',
'accts_gas',
'accts_cruise',
'accts_expedia',
'accts_travel_portal',
'accts_sb_capped_spend',
'refill_points_rewplus0',
'roundup_points_rewplus0',
'points_back_10ptc_resplus0',
'Incap_2x_points_back_rewplus0',
'metcap_1x_points_back_rewplus0',
'acq_bonus_points0',
'bonus_points0',
'spend_contactless',
'spend_online',
'spend_regular',
'txn_contactless',
'txn_online',
'txn_regular',
'accts_contactless',
'accts_online',
'accts_regular',
'acq_pre_preferred',
'acq_pre_premier',
'acq_pre_prestige',
'acq_pre_rplus',
'acq_pre_customcash',
'acq_pre_drivers_edge',
'acq_pre_simplicity',
'acq_pre_dp',
'acq_pre_oth_nonrewards',
'acq_pre_dc',
'acq_pre_dividend',
'acq_pre_oth_cash',
'acq_pre_aa',
'acq_pre_costco',
'acq_pre_oth_cobrands',
'acq_pre_others',
'ecm_pre_preferred',
'ecm_pre_premier',
'ecm_pre_prestige',
'ecm_pre_rplus',
'ecm_pre_customcash',
'ecm_pre_drivers_edge',
'ecm_pre_simplicity',
'ecm_pre_dp',
'ecm_pre_oth_nonrewards',
'ecm_pre_dc',
'ecm_pre_dividend',
'ecm_pre_oth_cash',
'ecm_pre_aa',
'ecm_pre_costco',
'ecm_pre_oth_cobrands',
'ecm_pre_others',
'points_earned_sp',
'points_earned_base_sp',
'points_redeemed_sp',
'point_balance',
'points_earned',
'earners',
'points_earned_base',
'base_earners',
'points_earned_bonus',
'bonus_earners',
'points_redeem',
'redeemers',
'points_redeemed_gc',
'gc_redeeners',
'points_redeemed_trvl',
'trvl_redeemers',
'points_redeemed_merch',
'merch_redeemers',
'points_redeemed_amazon',
'amazon_redeemers',
'accounts',
'members',
'yr',
'mon',
'monyr',
'monyyrchan'])

df_card_port_cons
num_rows=10000
np.random.seed(42)

def find_pernum(date):
    month=int(date[4:])
    year=int(date[:4])
    start_pernum, start_month, start_year=6405, 1, 2017
    year_diff = year - start_year
    pernum = start_pernum + 12 * year_diff + month - 1
    return pernum

all_yyyymm = [str(year) + str(month).zfill(2) for year in range(2017, 2023) for month in range(1, 13)]
all_yyyymm = [yyyymm for yyyymm in all_yyyymm if yyyymm <= '202309']
all_yyyymm = [yyyymm for yyyymm in all_yyyymm if yyyymm >= '201606']
ran_yyyymm = [random.choice(all_yyyymm) for _ in range(num_rows)]

df_card_port_cons ['per_num_yyyymm']= ran_yyyymm

df_card_port_cons ['per_num_yyyy']=df_card_port_cons ['per_num_yyyymm'].str[:4]
df_card_port_cons ['per_num_mm']=df_card_port_cons ['per_num_yyyymm'].str[4:]
df_card_port_cons ['per_num']=df_card_port_cons ['per_num_yyyymm'].apply(find_pernum)

df_card_port_cons['vintage'] = ['P' + yyyymm[:4] if int(yyyymm[:4]) <= 2017 else 'V' + yyyymm[:4] for yyyymm in ran_yyyymm]

product = ['AA Platinum', 'AA Executive', 'AA Gold', 'AA Mileup Bronze', 'ATT_Platinum',
           'ATT_Access More', 'ATT_Rewards', 'ATT_Access', 'Dividend', 'Double Cash', 
           'Costco Front Book', 'Costco Back Book', 'Expedia_Rewards', 'Expedia_Fee', 
           'Expedia_NoFee', 'Expedia_Rewards Voyager', 'Rewards+', 'Premier', 'Prestige', 
           'Preferred', 'Drivers Edge', 'Custom Cash', 'DP', 'Simplicity','Secured']
df_card_port_cons['product'] = np.random.choice(product,df_card_port_cons.shape[0],p=[0.08,0.012,0.016,0.016,0.007,0.005,0.011,0.001,0.001,
                                                                                      0.12,0.16,0.17,0.001,0.001,0.001,0.001,0.04,0.011,
                                                                                      0.001,0.11,0.004,0.035,0.112,0.08,0.004])

df_card_port_cons['prod_grp'] = df_card_port_cons['product'].map({
'AA Platinum':'AA',
'AA Executive':'AA',
'AA Gold':'AA',
'AA Mileup Bronze':'AA',
'ATT_Platinum':'ATT',
'ATT_Access More':'ATT',
'ATT_Rewards':'ATT',
'ATT_Access':'ATT',
'Dividend':'Cash',
'Double Cash':'Cash',
'Costco Front Book':'Costco',
'Costco Back Book':'Costco',
'Expedia_Rewards':'Expedia',
'Expedia_Fee':'Expedia',
'Expedia_NoFee':'Expedia',
'Expedia_Rewards Voyager':'Expedia',
'Rewards+':'TY',
'Premier':'TY',
'Prestige':'TY',
'Preferred':'TY',
'Drivers Edge':'TY',
'Custom Cash':'Cash',
'DP':'Value',
'Simplicity':'Value',
'Secured':'Value'
})


df_card_port_cons['prod_type'] = df_card_port_cons['product'].map({
'AA Platinum':'Cobrand',
'AA Executive':'Cobrand',
'AA Gold':'Cobrand',
'AA Mileup Bronze':'Cobrand',
'ATT_Platinum':'Cobrand',
'ATT_Access More':'Cobrand',
'ATT_Rewards':'Cobrand',
'ATT_Access':'Cobrand',
'Dividend':'PPM',
'Double Cash':'PPM',
'Costco Front Book':'Cobrand',
'Costco Back Book':'Cobrand',
'Expedia_Rewards':'Cobrand',
'Expedia_Fee':'Cobrand',
'Expedia_NoFee':'Cobrand',
'Expedia_Rewards Voyager':'Cobrand',
'Rewards+':'PPM',
'Premier':'PPM',
'Prestige':'PPM',
'Preferred':'PPM',
'Drivers Edge':'PPM',
'Custom Cash':'PPM',
'DP':'PPM',
'Simplicity':'PPM',
'Secured':'PPM'
})

wallet_size = ['HW', 'LW', 'MW', 'NULL', 'VHW']
wallet_segment_mapping = {
    'HW': 'HWR',
    'HW': 'HWT',
    'LW': 'LWR',
    'LW': 'LWT',
    'MW': 'MWR',
    'MW': 'MWT',
    'NULL': '',
    'VHW': 'HWT',
    'VHW': 'HWR'
}

df_card_port_cons['wallet_size'] = np.random.choice(wallet_size, df_card_port_cons.shape[0], p=[0.23, 0.21, 0.21, 0.14, 0.21])
df_card_port_cons['wallet_segment'] = df_card_port_cons['wallet_size'].map(wallet_segment_mapping)

df_card_port_cons

,per_num,vintage,product,prod_grp,prod_type,wallet_size,wallet_segment,cfo_revlv_ind,open_ind,spend_type,...,amazon_redeemers,accounts,members,yr,mon,monyr,monyyrchan,per_num_yyyymm,per_num_yyyy,per_num_mm
0,6412,P2017,Costco Front Book,Costco,Cobrand,LW,LWT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201708,2017,08
1,6471,V2022,Simplicity,Value,PPM,LW,LWT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202207,2022,07
2,6419,V2018,Preferred,TY,PPM,HW,HWT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201803,2018,03
3,6454,V2021,Costco Back Book,Costco,Cobrand,MW,MWT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202102,2021,02
4,6453,V2021,Double Cash,Cash,PPM,MW,MWT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202101,2021,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,6465,V2022,DP,Value,PPM,VHW,HWR,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202201,2022,01
9996,6407,P2017,DP,Value,PPM,HW,HWT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201703,2017,03
9997,6465,V2022,Simplicity,Value,PPM,LW,LWT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202201,2022,01
9998,6450,V2020,Costco Front Book,Costco,Cobrand,MW,MWT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202010,2020,10
9999,6433,V2019,Double Cash,Cash,PPM,HW,HWT,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201905,2019,05

In [3]:
np.random.seed(42)
df_card_port_cons['cfo_revlv_ind'] = np.random.choice([1,0], num_rows, p=[0.518,0.482])
df_card_port_cons['open_ind'] = np.random.choice([1,0], num_rows, p=[0.919,0.081])
df_card_port_cons['spend_type'] = np.random.choice([np.nan,2.0,3.0,1.0], num_rows, p=[0.291,0.262,0.247,0.2])
df_card_port_cons['segment'] = np.random.choice(["cm_ecm_conv","citi_ecm_conv"], num_rows, p=[0.563,0.437])
df_card_port_cons['ga_ind'] = np.random.choice([1,0], num_rows, p=[0.079,0.921])
df_card_port_cons['graduated_ind'] = np.random.choice([1,0], num_rows, p=[0.069,0.931])
df_card_port_cons['conv_ind'] = np.random.choice(["NULL","All others conversion"], num_rows, p=[0.529,0.471])
df_card_port_cons['college_ind'] = np.random.choice([1.0,np.nan], num_rows, p=[0.135,0.865])
df_card_port_cons['accts_enr'] = np.random.uniform(1, 1738, num_rows)
df_card_port_cons['accts_open'] = np.random.uniform(0, 1367, num_rows)
df_card_port_cons['accts_active_bill'] = np.random.uniform(0, 940, num_rows)
df_card_port_cons['accts_active_sales'] = np.random.uniform(0, 568, num_rows)
df_card_port_cons['accts_bill_inactv_l12'] = np.random.uniform(0, 429, num_rows)
df_card_port_cons['accts_sales_inactive_l12'] = np.random.uniform(0, 173, num_rows)
df_card_port_cons['accts_new_acquired'] = np.random.uniform(0, 6, num_rows)
df_card_port_cons['accts_closed_new'] = np.random.uniform(0, 6, num_rows)
df_card_port_cons['accts_closed_vol'] = np.random.uniform(0, 2, num_rows)
df_card_port_cons['accts_closed_invol'] = np.random.uniform(0, 5, num_rows)
df_card_port_cons['accts_inactive_closed'] = np.random.uniform(0, 1, num_rows)
df_card_port_cons['accts_otherinvol_closed'] = np.random.uniform(0, 3, num_rows)
df_card_port_cons['accts_new_balcon'] = np.random.uniform(0, 6, num_rows)
df_card_port_cons['accts_enr_delq_26'] = np.random.uniform(0, 16, num_rows)
df_card_port_cons['accts_ncl'] = np.random.uniform(0, 3, num_rows)
df_card_port_cons['fico_score'] = np.random.uniform(0, 1168672, num_rows)
df_card_port_cons['fico_score_accts'] = np.random.uniform(0, 1520, num_rows)
df_card_port_cons['accts_acctonlin_ever'] = np.random.uniform(0, 1283, num_rows)
df_card_port_cons['accts_paperless_ever'] = np.random.uniform(0, 880, num_rows)
df_card_port_cons['accts_auth_primary_only'] = np.random.uniform(0, 1410, num_rows)
df_card_port_cons['accts_auth_secondary'] = np.random.uniform(0, 2714, num_rows)
df_card_port_cons['accts_auth_multiple'] = np.random.uniform(0, 21, num_rows)
df_card_port_cons['sales_purch'] = np.random.uniform(0, 566452, num_rows)
df_card_port_cons['sales_offus'] = np.random.uniform(0, 1549669, num_rows)
df_card_port_cons['sales_new_balcon_ant'] = np.random.uniform(0, 32799, num_rows)
df_card_port_cons['bal_anr'] = np.random.uniform(-26884, 2254209, num_rows)
df_card_port_cons['bal_enr'] = np.random.uniform(-944502, 2237576, num_rows)
df_card_port_cons['bal_bnr'] = np.random.uniform(-47200, 2288318, num_rows)
df_card_port_cons['bal_delnq_26'] = np.random.uniform(0, 73906, num_rows)
df_card_port_cons['bal_full_rate_offus'] = np.random.uniform(0, 5115604, num_rows)
df_card_port_cons['bal_promo_offus'] = np.random.uniform(0, 1546437, num_rows)
df_card_port_cons['bal_rvlv_offus_bur'] = np.random.uniform(0, 12316020, num_rows)
df_card_port_cons['bal_rvlv_offus_argus'] = np.random.uniform(0, 7288586, num_rows)
df_card_port_cons['credit_limit_onus'] = np.random.uniform(200, 16668840, num_rows)
df_card_port_cons['pay_amt'] = np.random.uniform(0, 652740, num_rows)
df_card_port_cons['pay_rate'] = np.random.uniform(-350130270, 350493437, num_rows)
df_card_port_cons['bal_revolving'] = np.random.uniform(0, 2018455, num_rows)
df_card_port_cons['net_interest'] = np.random.uniform(-275485, 21306, num_rows)
df_card_port_cons['cof'] = np.random.uniform(-1377, 3247, num_rows)
df_card_port_cons['interchange'] = np.random.uniform(-4174, 10313, num_rows)
df_card_port_cons['fee_total'] = np.random.uniform(-106235, 4647, num_rows)
df_card_port_cons['rebate'] = np.random.uniform(-6711, 7277, num_rows)
df_card_port_cons['cnr'] = np.random.uniform(-245709, 25510, num_rows)
df_card_port_cons['ebit'] = np.random.uniform(-3705029, 13061, num_rows)
df_card_port_cons['ncl'] = np.random.uniform(0, 12054, num_rows)
df_card_port_cons['refill_points_rewplus'] = np.random.uniform(0, 2672, num_rows)
df_card_port_cons['roundup_points_rewplus'] = np.random.uniform(0, 1230, num_rows)
df_card_port_cons['points_back_10ptc_rewplus'] = np.random.uniform(0, 0, num_rows)
df_card_port_cons['Incap_2x_points_back_rewplus'] = np.random.uniform(0, 3966, num_rows)
df_card_port_cons['metacap_1x_points_back_rewplus'] = np.random.uniform(0, 85, num_rows)
df_card_port_cons['acq_bonus_points'] = np.random.uniform(0, 22789, num_rows)
df_card_port_cons['bonus_points'] = np.random.uniform(-81943, 76279, num_rows)
df_card_port_cons['bal_bseg_intro_bt'] = np.random.uniform(0, 276479, num_rows)
df_card_port_cons['bal_bseg_intro_spl'] = np.random.uniform(0, 39108, num_rows)
df_card_port_cons['bal_bseg_intro_purch_promo'] = np.random.uniform(-2216, 64368, num_rows)
df_card_port_cons['bal_bseg_intro_others'] = np.random.uniform(0, 0, num_rows)
df_card_port_cons['bal_bseg_goto'] = np.random.uniform(-932292, 171275, num_rows)
df_card_port_cons['bal_bseg_risk'] = np.random.uniform(-24031, 178682, num_rows)
df_card_port_cons['bal_bseg_flex_loan'] = np.random.uniform(0, 16982, num_rows)
df_card_port_cons['bal_bseg_flex_pay'] = np.random.uniform(0, 3111, num_rows)
df_card_port_cons['bal_bseg_amazon_pos'] = np.random.uniform(0, 946, num_rows)
df_card_port_cons['accts_bseg_flex_loan'] = np.random.uniform(0, 28, num_rows)
df_card_port_cons['accts_bseg_flex_pay'] = np.random.uniform(0, 174, num_rows)
df_card_port_cons['accts_bseg_amazon_pos'] = np.random.uniform(0, 144, num_rows)
df_card_port_cons['sales_bseg_flex_loan'] = np.random.uniform(0, 1318, num_rows)
df_card_port_cons['sales_bseg_flex_pay'] = np.random.uniform(0, 934, num_rows)
df_card_port_cons['sales_bseg_amazon_pos'] = np.random.uniform(0, 430, num_rows)
df_card_port_cons['expedia_sales'] = np.random.uniform(0, 1292, num_rows)
df_card_port_cons['travel_portal_sales'] = np.random.uniform(0, 51, num_rows)
df_card_port_cons['sb_capped_spend'] = np.random.uniform(0, 0, num_rows)
df_card_port_cons['spend1_airlines'] = np.random.uniform(0, 8703, num_rows)
df_card_port_cons['txn_airlines'] = np.random.uniform(0, 30, num_rows)
df_card_port_cons['spend1_dining'] = np.random.uniform(0, 52669, num_rows)
df_card_port_cons['txn_dining'] = np.random.uniform(0, 1835, num_rows)
df_card_port_cons['spend1_entertainment'] = np.random.uniform(0, 7242, num_rows)
df_card_port_cons['txn_entertainment'] = np.random.uniform(0, 244, num_rows)
df_card_port_cons['spend1_electronics'] = np.random.uniform(0, 13368, num_rows)
df_card_port_cons['txn_electronics'] = np.random.uniform(0, 43, num_rows)
df_card_port_cons['spend1_home_Improvement'] = np.random.uniform(0, 92639, num_rows)
df_card_port_cons['txn_house_improvement'] = np.random.uniform(0, 429, num_rows)
df_card_port_cons['spend1_grocery'] = np.random.uniform(0, 85567, num_rows)
df_card_port_cons['txn_grocery'] = np.random.uniform(0, 1539, num_rows)
df_card_port_cons['spend1_hotels_motels'] = np.random.uniform(0, 17868, num_rows)
df_card_port_cons['txn_hotels_motels'] = np.random.uniform(0, 56, num_rows)
df_card_port_cons['spend_other_travel'] = np.random.uniform(0, 11106, num_rows)
df_card_port_cons['spend_gas'] = np.random.uniform(0, 30472, num_rows)
df_card_port_cons['txn_gas'] = np.random.uniform(0, 1166, num_rows)
df_card_port_cons['txn_other_travel'] = np.random.uniform(0, 147, num_rows)
df_card_port_cons['spend_cruise'] = np.random.uniform(0, 867, num_rows)
df_card_port_cons['txn_cruise'] = np.random.uniform(0, 1, num_rows)
df_card_port_cons['spend1_total'] = np.random.uniform(2, 785910, num_rows)
df_card_port_cons['txn_total'] = np.random.uniform(1, 10261, num_rows)
df_card_port_cons['accts_airlines'] = np.random.uniform(0, 11, num_rows)
df_card_port_cons['accts_dining'] = np.random.uniform(0, 223, num_rows)
df_card_port_cons['accts_entertainment'] = np.random.uniform(0, 77, num_rows)
df_card_port_cons['accts_electronics'] = np.random.uniform(0, 22, num_rows)
df_card_port_cons['accts_home_improvement'] = np.random.uniform(0, 118, num_rows)
df_card_port_cons['accts_grocery'] = np.random.uniform(0, 227, num_rows)
df_card_port_cons['accts_hotels_motels'] = np.random.uniform(0, 25, num_rows)
df_card_port_cons['accts_other_travel'] = np.random.uniform(0, 44, num_rows)
df_card_port_cons['accts_gas'] = np.random.uniform(0, 217, num_rows)
df_card_port_cons['accts_cruise'] = np.random.uniform(0, 0.5, num_rows)
df_card_port_cons['accts_expedia'] = np.random.uniform(0, 2, num_rows)
df_card_port_cons['accts_travel_portal'] = np.random.uniform(0, 0.1, num_rows)
df_card_port_cons['accts_sb_capped_spend'] = np.random.uniform(0, 0, num_rows)
df_card_port_cons['refill_points_rewplus0'] = np.random.uniform(0, 2672, num_rows)
df_card_port_cons['roundup_points_rewplus0'] = np.random.uniform(0, 1230, num_rows)
df_card_port_cons['points_back_10ptc_resplus0'] = np.random.uniform(0, 0, num_rows)
df_card_port_cons['Incap_2x_points_back_rewplus0'] = np.random.uniform(0, 3966, num_rows)
df_card_port_cons['metcap_1x_points_back_rewplus0'] = np.random.uniform(0, 85, num_rows)
df_card_port_cons['acq_bonus_points0'] = np.random.uniform(0, 22789, num_rows)
df_card_port_cons['bonus_points0'] = np.random.uniform(-81943, 76279, num_rows)
df_card_port_cons['spend_contactless'] = np.random.uniform(0, 14957, num_rows)
df_card_port_cons['spend_online'] = np.random.uniform(0, 228334, num_rows)
df_card_port_cons['spend_regular'] = np.random.uniform(0, 544348, num_rows)
df_card_port_cons['txn_contactless'] = np.random.uniform(0, 214, num_rows)
df_card_port_cons['txn_online'] = np.random.uniform(0, 2455, num_rows)
df_card_port_cons['txn_regular'] = np.random.uniform(0, 7610, num_rows)
df_card_port_cons['accts_contactless'] = np.random.uniform(0, 84, num_rows)
df_card_port_cons['accts_online'] = np.random.uniform(0, 458, num_rows)
df_card_port_cons['accts_regular'] = np.random.uniform(0, 800, num_rows)
df_card_port_cons['acq_pre_preferred'] = np.random.uniform(0, 203, num_rows)
df_card_port_cons['acq_pre_premier'] = np.random.uniform(0, 23, num_rows)
df_card_port_cons['acq_pre_prestige'] = np.random.uniform(0, 3, num_rows)
df_card_port_cons['acq_pre_rplus'] = np.random.uniform(0, 83, num_rows)
df_card_port_cons['acq_pre_customcash'] = np.random.uniform(0, 0, num_rows)
df_card_port_cons['acq_pre_drivers_edge'] = np.random.uniform(0, 8, num_rows)
df_card_port_cons['acq_pre_simplicity'] = np.random.uniform(0, 214, num_rows)
df_card_port_cons['acq_pre_dp'] = np.random.uniform(0, 278, num_rows)
df_card_port_cons['acq_pre_oth_nonrewards'] = np.random.uniform(0, 6, num_rows)
df_card_port_cons['acq_pre_dc'] = np.random.uniform(0, 272, num_rows)
df_card_port_cons['acq_pre_dividend'] = np.random.uniform(0, 110, num_rows)
df_card_port_cons['acq_pre_oth_cash'] = np.random.uniform(0, 9, num_rows)
df_card_port_cons['acq_pre_aa'] = np.random.uniform(0, 197, num_rows)
df_card_port_cons['acq_pre_costco'] = np.random.uniform(0, 576, num_rows)
df_card_port_cons['acq_pre_oth_cobrands'] = np.random.uniform(0, 69, num_rows)
df_card_port_cons['acq_pre_others'] = np.random.uniform(0, 2, num_rows)
df_card_port_cons['ecm_pre_preferred'] = np.random.uniform(0, 16, num_rows)
df_card_port_cons['ecm_pre_premier'] = np.random.uniform(0, 5, num_rows)
df_card_port_cons['ecm_pre_prestige'] = np.random.uniform(0, 1.5, num_rows)
df_card_port_cons['ecm_pre_rplus'] = np.random.uniform(0, 1, num_rows)
df_card_port_cons['ecm_pre_customcash'] = np.random.uniform(0, 0, num_rows)
df_card_port_cons['ecm_pre_drivers_edge'] = np.random.uniform(0, 35, num_rows)
df_card_port_cons['ecm_pre_simplicity'] = np.random.uniform(0, 3, num_rows)
df_card_port_cons['ecm_pre_dp'] = np.random.uniform(0, 42, num_rows)
df_card_port_cons['ecm_pre_oth_nonrewards'] = np.random.uniform(0, 183, num_rows)
df_card_port_cons['ecm_pre_dc'] = np.random.uniform(0, 87, num_rows)
df_card_port_cons['ecm_pre_dividend'] = np.random.uniform(0, 65, num_rows)
df_card_port_cons['ecm_pre_oth_cash'] = np.random.uniform(0, 0.5, num_rows)
df_card_port_cons['ecm_pre_aa'] = np.random.uniform(0, 56, num_rows)
df_card_port_cons['ecm_pre_costco'] = np.random.uniform(0, 2, num_rows)
df_card_port_cons['ecm_pre_oth_cobrands'] = np.random.uniform(0, 6, num_rows)
df_card_port_cons['ecm_pre_others'] = np.random.uniform(0, 1325, num_rows)
df_card_port_cons['points_earned_sp'] = np.random.uniform(-32307, 296973, num_rows)
df_card_port_cons['points_earned_base_sp'] = np.random.uniform(-13593, 207348, num_rows)
df_card_port_cons['points_redeemed_sp'] = np.random.uniform(-255031, 0, num_rows)
df_card_port_cons['point_balance'] = np.random.uniform(-53279, 6137920, num_rows)
df_card_port_cons['points_earned'] = np.random.uniform(-23882, 398917, num_rows)
df_card_port_cons['earners'] = np.random.uniform(0, 307, num_rows)
df_card_port_cons['points_earned_base'] = np.random.uniform(-8235, 282081, num_rows)
df_card_port_cons['base_earners'] = np.random.uniform(0, 287, num_rows)
df_card_port_cons['points_earned_bonus'] = np.random.uniform(-27086, 144083, num_rows)
df_card_port_cons['bonus_earners'] = np.random.uniform(0, 207, num_rows)
df_card_port_cons['points_redeem'] = np.random.uniform(-532931, 2888, num_rows)
df_card_port_cons['redeemers'] = np.random.uniform(0, 54, num_rows)
df_card_port_cons['points_redeemed_gc'] = np.random.uniform(-194846, -900, num_rows)
df_card_port_cons['gc_redeeners'] = np.random.uniform(0, 7, num_rows)
df_card_port_cons['points_redeemed_trvl'] = np.random.uniform(-92609, 71612, num_rows)
df_card_port_cons['trvl_redeemers'] = np.random.uniform(0, 1, num_rows)
df_card_port_cons['points_redeemed_merch'] = np.nan
df_card_port_cons['merch_redeemers'] = np.random.uniform(0, 0, num_rows)
df_card_port_cons['points_redeemed_amazon'] = np.random.uniform(-301485, 1087, num_rows)
df_card_port_cons['amazon_redeemers'] = np.random.uniform(0, 34, num_rows)
df_card_port_cons['accounts'] = np.random.uniform(0, 214, num_rows)
df_card_port_cons['members'] = np.random.uniform(0, 214, num_rows)
df_card_port_cons['yr'] = "2020"
df_card_port_cons['mon'] = "Sep"
df_card_port_cons['monyr'] = "Sep-20"
df_card_port_cons['monyrchar'] = "Sep'2020"

/tmp/ipykernel_102/2943305882.py:188: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_card_port_cons['monyrchar'] = "Sep'2020"

In [5]:
table_name = 'card_port_cons_'
df_card_port_cons.columns = [table_name + str(i) for i in df_card_port_cons.columns]

df_info = pd.DataFrame(columns=['column_name', 'Data_type'])
df_info['column_name'] = df_card_port_cons.columns.tolist()
for i in range(df_info.shape[0]):
    df_info['Data_type'][i] = df_card_port_cons.iloc[:, i].dtype

df_card_port_cons.to_csv('df_card_port_cons.csv', index=False)
df_info.to_csv('df_card_port_cons_info.csv', index=False)

df_info

                                       column_name Data_type
0                           card_port_cons_per_num     int64
1                           card_port_cons_vintage    object
2                           card_port_cons_product    object
3                          card_port_cons_prod_grp    object
4                         card_port_cons_prod_type    object
..                                             ...       ...
196                      card_port_cons_per_num_mm    object
197               card_port_cons_credit_limit_onus   float64
198                     card_port_cons_interchange   float64
199  card_port_cons_metacap_1x_points_back_rewplus   float64
200                       card_port_cons_monyrchar    object

[201 rows x 2 columns]

In [4]:
df_card_port_cons

,per_num,vintage,product,prod_grp,prod_type,wallet_size,wallet_segment,cfo_revlv_ind,open_ind,spend_type,...,mon,monyr,monyyrchan,per_num_yyyymm,per_num_yyyy,per_num_mm,credit_limit_onus,interchange,metacap_1x_points_back_rewplus,monyrchar
0,6412,P2017,Costco Front Book,Costco,Cobrand,LW,LWT,1,1,3.0,...,Sep,Sep-20,NaN,201708,2017,08,4.590467e+06,-3914.363403,79.439180,Sep'2020
1,6471,V2022,Simplicity,Value,PPM,LW,LWT,0,1,NaN,...,Sep,Sep-20,NaN,202207,2022,07,6.779440e+05,5698.135998,38.375510,Sep'2020
2,6419,V2018,Preferred,TY,PPM,HW,HWT,0,1,2.0,...,Sep,Sep-20,NaN,201803,2018,03,1.627654e+07,3341.584051,31.203627,Sep'2020
3,6454,V2021,Costco Back Book,Costco,Cobrand,MW,MWT,0,1,3.0,...,Sep,Sep-20,NaN,202102,2021,02,3.917823e+06,9591.672649,42.458892,Sep'2020
4,6453,V2021,Double Cash,Cash,PPM,MW,MWT,1,1,2.0,...,Sep,Sep-20,NaN,202101,2021,01,1.509911e+07,987.198795,0.055677,Sep'2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,6465,V2022,DP,Value,PPM,VHW,HWR,0,1,1.0,...,Sep,Sep-20,NaN,202201,2022,01,1.455056e+07,5941.484815,46.223946,Sep'2020
9996,6407,P2017,DP,Value,PPM,HW,HWT,0,1,3.0,...,Sep,Sep-20,NaN,201703,2017,03,2.692071e+06,8175.377849,12.191742,Sep'2020
9997,6465,V2022,Simplicity,Value,PPM,LW,LWT,0,1,NaN,...,Sep,Sep-20,NaN,202201,2022,01,1.627157e+07,8415.259144,51.146728,Sep'2020
9998,6450,V2020,Costco Front Book,Costco,Cobrand,MW,MWT,1,1,2.0,...,Sep,Sep-20,NaN,202010,2020,10,2.030478e+06,-4083.431715,53.203818,Sep'2020
9999,6433,V2019,Double Cash,Cash,PPM,HW,HWT,1,1,NaN,...,Sep,Sep-20,NaN,201905,2019,05,1.621768e+07,4293.925431,58.781565,Sep'2020